/* DO NOT EDIT THIS FILE - it is machine generated */
#include <android/log.h>
#include <jni.h>
#include <stddef.h>
#include "FlyLog.h"
/* Header for class com_flyzebra_rtmp_RtmpClient */

#ifndef _Included_com_flyzebra_rtmp_RtmpClient
#define _Included_com_flyzebra_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif

 JNIEXPORT jlong JNICALL Java_com_flyzebra_rtmp_RtmpDump_open
 (JNIEnv * env, jclass thiz, jstring url_, jboolean isPublishMode);
/*
 * Class:     com_flyzebra_rtmp_RtmpClient
 * Method:    read
 * Signature: ([CI)I
 */
 JNIEXPORT jint JNICALL Java_com_flyzebra_rtmp_RtmpDump_read
 (JNIEnv * env, jclass thiz,jlong rtmp, jbyteArray data_, jint offset, jint size);

/*
 * Class:     com_flyzebra_rtmp_RtmpClient
 * Method:    write
 * Signature: ([CI)I
 */
 JNIEXPORT jint JNICALL Java_com_flyzebra_rtmp_RtmpDump_write
 (JNIEnv * env, jclass thiz,jlong rtmp, jbyteArray data, jint size, jint type, jint ts);

/*
 * Class:     com_flyzebra_rtmp_RtmpClient
 * Method:    close
 * Signature: ()I
 */
 JNIEXPORT jint JNICALL Java_com_flyzebra_rtmp_RtmpDump_close
 (JNIEnv * env, jclass thiz, jlong rtmp);

#ifdef __cplusplus
}
#endif
#endif
